[env:esp8266-tcp]
platform = espressif8266
framework = arduino
board = nodemcuv2
lib_deps = file://../..

[env:esp8266-tls]
platform = espressif8266
framework = arduino
board = nodemcuv2
lib_deps = file://../..
build_flags = -DRMTT_USE_TLS
